<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TargetFramework>net9.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CassandraCSharpDriver" Version="3.20.1" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.6.141">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Garcia.Exceptions.Cassandra\Garcia.Exceptions.Cassandra.csproj" />
	</ItemGroup>

</Project>
