<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<TargetFramework>net9.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RabbitMQ.Client" Version="7.0.0" />
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.7.115">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Garcia.Application.RabbitMQ\Garcia.Application.RabbitMQ.csproj" />
		<ProjectReference Include="..\Garcia.Infrastructure\Garcia.Infrastructure.csproj" />
	</ItemGroup>

</Project>
