<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TargetFramework>net9.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
		<PackageReference Include="Nerdbank.GitVersioning" Version="3.7.115">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Garcia.Infrastructure.Identity\Garcia.Infrastructure.Identity.csproj" />
		<ProjectReference Include="..\Garcia.Persistence.EntityFramework\Garcia.Persistence.EntityFramework.csproj" />
	</ItemGroup>

</Project>
