//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GarciaCore.CodeGenerator {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using GarciaCore.CodeGenerator;
    using System;
    
    
    public partial class BaseTemplate : BaseTemplateBase {
        
        
        #line 10 ""

protected Generator generator;

public BaseTemplate() 
{
    this.generator = this.CreateGenerator();
}
    
protected virtual Generator CreateGenerator()
{
    return null; 
}

public void test()
{
}

        #line default
        #line hidden
        
        
        #line 27 ""

        this.Write(" ");

        #line default
        #line hidden
        
        
        private GarciaCore.CodeGenerator.Item _ItemField;

        public GarciaCore.CodeGenerator.Item Item {
            get {
                return this._ItemField;
            }
        }

        private string _NamespaceField;

        public string Namespace {
            get {
                return this._NamespaceField;
            }
        }

        private string _IncludesField;

        public string Includes {
            get {
                return this._IncludesField;
            }
        }

        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                bool _ItemAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("Item"))) {
                    object data = this.Session["Item"];
                    if (typeof(GarciaCore.CodeGenerator.Item).IsAssignableFrom(data.GetType())) {
                        this._ItemField = ((GarciaCore.CodeGenerator.Item)(data));
                        _ItemAcquired = true;
                    }
                    else {
                        this.Error("The type \'GarciaCore.CodeGenerator.Item\' of the parameter \'Item\' did not match th" +
                                "e type passed to the template");
                    }
                }
                if ((_ItemAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Item");
                    if ((data != null)) {
                        if (typeof(GarciaCore.CodeGenerator.Item).IsAssignableFrom(data.GetType())) {
                            this._ItemField = ((GarciaCore.CodeGenerator.Item)(data));
                            _ItemAcquired = true;
                        }
                        else {
                            this.Error("The type \'GarciaCore.CodeGenerator.Item\' of the parameter \'Item\' did not match th" +
                                    "e type passed to the template");
                        }
                    }
                }
                bool _NamespaceAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("Namespace"))) {
                    object data = this.Session["Namespace"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._NamespaceField = ((string)(data));
                        _NamespaceAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'Namespace\' did not match the type pass" +
                                "ed to the template");
                    }
                }
                if ((_NamespaceAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._NamespaceField = ((string)(data));
                            _NamespaceAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'Namespace\' did not match the type pass" +
                                    "ed to the template");
                        }
                    }
                }
                bool _IncludesAcquired = false;
                if (((this.Session != null) 
                            && this.Session.ContainsKey("Includes"))) {
                    object data = this.Session["Includes"];
                    if (typeof(string).IsAssignableFrom(data.GetType())) {
                        this._IncludesField = ((string)(data));
                        _IncludesAcquired = true;
                    }
                    else {
                        this.Error("The type \'System.String\' of the parameter \'Includes\' did not match the type passe" +
                                "d to the template");
                    }
                }
                if ((_IncludesAcquired == false)) {
                    object data = System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Includes");
                    if ((data != null)) {
                        if (typeof(string).IsAssignableFrom(data.GetType())) {
                            this._IncludesField = ((string)(data));
                            _IncludesAcquired = true;
                        }
                        else {
                            this.Error("The type \'System.String\' of the parameter \'Includes\' did not match the type passe" +
                                    "d to the template");
                        }
                    }
                }
            }

        }
    }
    
    public class BaseTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
