// ------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod bir araç tarafýndan oluþturuldu.
//     Çalýþma Zamaný Sürümü: 17.0.0.0
//  
//     Bu dosyada yapýlacak deðiþiklikler hatalý davranýþa neden olabilir ve
//     kod yeniden üretildiðinde kaybolabilir.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GarciaCore.CodeGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using GarciaCore.CodeGenerator;
    using GarciaCore.Infrastructure;
    using GarciaCore.Application;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Seçkin\source\repos\garciacore\src\GarciaCore.CodeGenerator\CQRSWebApiDeleteCommandTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CQRSWebApiDeleteCommandTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n\tThis file was generated automatically by Garcia Framework. \r\n\tDo not edit ma" +
                    "nually. \r\n\tAdd a new partial class with the same name if you want to add extra f" +
                    "unctionality.\r\n*/");
            this.Write("\r\n");
            this.Write(@"using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using GarciaCore.Infrastructure;
using GarciaCore.Domain;
using GarciaCore.Persistence;
using System.Threading;
using System.Threading.Tasks;");
            this.Write("  \r\nusing MediatR;\r\n\r\nnamespace ");
            
            #line 13 "C:\Users\Seçkin\source\repos\garciacore\src\GarciaCore.CodeGenerator\CQRSWebApiDeleteCommandTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    public partial class Delete");
            
            #line 15 "C:\Users\Seçkin\source\repos\garciacore\src\GarciaCore.CodeGenerator\CQRSWebApiDeleteCommandTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("Command : ");
            
            #line 15 "C:\Users\Seçkin\source\repos\garciacore\src\GarciaCore.CodeGenerator\CQRSWebApiDeleteCommandTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseClass));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        public ");
            
            #line 17 "C:\Users\Seçkin\source\repos\garciacore\src\GarciaCore.CodeGenerator\CQRSWebApiDeleteCommandTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(IdTypeName));
            
            #line default
            #line hidden
            this.Write(" Id { get; set; }\r\n    }\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 21 "C:\Users\Seçkin\source\repos\garciacore\src\GarciaCore.CodeGenerator\CQRSWebApiDeleteCommandTemplate.tt"

    protected override Generator CreateGenerator()
	{
		return new CQRSWebApiDeleteCommandGenerator();
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
