// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GarciaCore.CodeGenerator
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\vehbi\source\repos\projects\garciacore\src\GarciaCore.CodeGenerator\ReactCRUDTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ReactCRUDTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("React code\r\n##pages\\Edit##\r\nEdit contents\r\n##pages\\List##\r\nList contents\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 8 "C:\Users\vehbi\source\repos\projects\garciacore\src\GarciaCore.CodeGenerator\ReactCRUDTemplate.tt"

    protected override Generator CreateGenerator()
	{
		return new ReactCRUDGenerator();
	}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
